# Generated by Django 5.0.6 on 2024-08-21 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 12, 54, 9, 986972, tzinfo=datetime.timezone.utc)),
        ),
    ]
