# Generated by Django 5.0.6 on 2024-06-25 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 7, 41, 24, 616285, tzinfo=datetime.timezone.utc)),
        ),
    ]
