# Generated by Django 5.0.6 on 2024-06-30 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_seller_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 8, 0, 41, 987320, tzinfo=datetime.timezone.utc)),
        ),
    ]
