# Generated by Django 5.0.6 on 2024-07-01 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_is_buyer_user_is_seller_alter_buyer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 8, 42, 1, 725515, tzinfo=datetime.timezone.utc)),
        ),
    ]
