# Generated by Django 5.0.6 on 2024-09-19 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_landproperty_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 11, 38, 33, 705652, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
