# Generated by Django 5.0.6 on 2024-09-30 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_user_subscription_end_date_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 4, 54, 31, 813762, tzinfo=datetime.timezone.utc)),
        ),
    ]
