# Generated by Django 5.0.6 on 2024-07-01 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_seller_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 16, 28, 17, 297733, tzinfo=datetime.timezone.utc)),
        ),
    ]
