# Generated by Django 5.0.6 on 2024-10-02 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_user_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 1, 5, 51, 44, 877850, tzinfo=datetime.timezone.utc)),
        ),
    ]
