# Generated by Django 5.0.6 on 2024-10-05 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_user_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 3, 59, 19, 159125, tzinfo=datetime.timezone.utc)),
        ),
    ]
