# Generated by Django 5.0.6 on 2024-07-04 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_seller_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 10, 23, 15, 759395, tzinfo=datetime.timezone.utc)),
        ),
    ]
