# Generated by Django 5.0.6 on 2024-07-07 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_seller_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 9, 2, 32, 494407, tzinfo=datetime.timezone.utc)),
        ),
    ]
