# Generated by Django 5.0.6 on 2024-07-08 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_seller_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 3, 47, 15, 665764, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_provider',
            field=models.CharField(default='email', max_length=50),
        ),
    ]
