# Generated by Django 5.0.6 on 2024-07-10 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_user_is_admin_alter_seller_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 4, 58, 38, 818624, tzinfo=datetime.timezone.utc)),
        ),
    ]
