# Generated by Django 5.0.6 on 2024-07-14 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 12, 50, 55, 700150, tzinfo=datetime.timezone.utc)),
        ),
    ]
