# Generated by Django 5.0.6 on 2024-07-18 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_seller_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 9, 37, 20, 209515, tzinfo=datetime.timezone.utc)),
        ),
    ]
