# Generated by Django 5.0.6 on 2024-07-19 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_seller_subscription_end_date_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landproperty',
            name='amenities',
            field=models.ManyToManyField(to='myapp.amenity'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 11, 54, 0, 15956, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
