# Generated by Django 5.0.6 on 2024-07-19 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_landproperty_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialproperty',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='residentialproperty',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 12, 5, 36, 612830, tzinfo=datetime.timezone.utc)),
        ),
    ]
