# Generated by Django 5.0.6 on 2024-07-20 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_residentialproperty_images_residentialproperty_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landproperty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residentialproperty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 6, 19, 42, 169631, tzinfo=datetime.timezone.utc)),
        ),
    ]
