# Generated by Django 5.0.6 on 2024-07-26 05:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_seller_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landproperty',
            name='images',
        ),
        migrations.RemoveField(
            model_name='residentialproperty',
            name='images',
        ),
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 5, 3, 4, 871547, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_provider',
            field=models.CharField(blank=True, default=(('email', 'email'), ('google', 'google'), ('facebook', 'facebook')), max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('land_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.landproperty')),
                ('residential_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.residentialproperty')),
            ],
        ),
    ]
