# Generated by Django 5.0.6 on 2024-07-26 06:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_landproperty_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='land_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.landproperty'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='residential_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.residentialproperty'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 6, 1, 46, 955073, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_provider',
            field=models.CharField(blank=True, default=(('email', 'email'), ('google', 'google'), ('facebook', 'facebook')), max_length=50, null=True),
        ),
    ]
