# Generated by Django 5.0.6 on 2024-07-30 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_propertyimage_land_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='subscription_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 29, 12, 41, 49, 431525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_provider',
            field=models.CharField(blank=True, default=(('email', 'email'), ('google', 'google'), ('facebook', 'facebook')), max_length=50, null=True),
        ),
    ]
