# Generated by Django 5.0.6 on 2024-09-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='property_content_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='property_object_id',
        ),
    ]
